##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Makefile for step1
##

FOLDER	=	../

CFLAG	=	-Wall -Wextra

SRC	=	$(FOLDER)main.c		\
		$(FOLDER)func.c		\
		$(FOLDER)rush.c		\

NAME	=	rush2

all	:	
		gcc -o $(NAME) $(CFLAG) $(SRC)

clean	:
		rm -f $(NAME)

re	:	clean all
